version = 1

[[analyzers]]
name = "docker"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "csharp"

[[transformers]]
name = "dotnet-format"

[[transformers]]
name = "prettier"