services:
  web:
    build:
      context: ./src/CrowdQR.API
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=db;Port=5432;Database=crowdqr;Username=postgres;Password=postgres
  
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crowdqr
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: