services:
  traefik:
    image: traefik:v3.0
    container_name: crowdqr-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    command:
      - --global.checkNewVersion=false
      - --global.sendAnonymousUsage=false
      - --api.dashboard=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=crowdqr-network
      - --certificatesresolvers.cloudflare.acme.email=${CLOUDFLARE_EMAIL}
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesresolvers.cloudflare.acme.dnschallenge.delaybeforecheck=30
      - --log.level=INFO
    networks:
      - crowdqr-network
    labels:
      - "traefik.enable=false"

  web:
    build:
      context: ./src
      dockerfile: CrowdQR.Web/Dockerfile
    image: ${REGISTRY:-ghcr.io}/${REPOSITORY:-grayplex/crowdqr}-web:${CROWDQR_VERSION:-latest}
    container_name: crowdqr-web
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ApiSettings__BaseUrl=http://api:5000
      - ApiSettings__PublicUrl=https://api.${DOMAIN}
    depends_on:
      api:
        condition: service_healthy
    expose:
      - "80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - crowdqr-network
    labels:
      - "traefik.enable=true"
      
      # HTTPS Web Routes
      - "traefik.http.routers.web-secure.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.web-secure.entrypoints=websecure"
      - "traefik.http.routers.web-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.web-secure.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.web-secure.tls.domains[0].sans=www.${DOMAIN}"
      - "traefik.http.routers.web-secure.service=web-service"
      
      # HTTP to HTTPS Redirect
      - "traefik.http.routers.web-insecure.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.web-insecure.entrypoints=web"
      - "traefik.http.routers.web-insecure.middlewares=web-redirect-https"
      
      # Service Definition
      - "traefik.http.services.web-service.loadbalancer.server.port=80"
      
      # Middleware for HTTPS Redirect
      - "traefik.http.middlewares.web-redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.web-redirect-https.redirectscheme.permanent=true"

  api:
    build:
      context: ./src
      dockerfile: CrowdQR.Api/Dockerfile
    image: ${REGISTRY:-ghcr.io}/${REPOSITORY:-grayplex/crowdqr}-api:${CROWDQR_VERSION:-latest}
    container_name: crowdqr-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER:-CrowdQR.Api}
      - JWT_AUDIENCE=${JWT_AUDIENCE:-CrowdQR.Web}
    expose:
      - "5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - crowdqr-network
    labels:
      - "traefik.enable=true"
      
      # HTTPS API Routes
      - "traefik.http.routers.api-secure.rule=Host(`api.${DOMAIN}`)"
      - "traefik.http.routers.api-secure.entrypoints=websecure"
      - "traefik.http.routers.api-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.api-secure.service=api-service"
      
      # HTTP to HTTPS Redirect for API
      - "traefik.http.routers.api-insecure.rule=Host(`api.${DOMAIN}`)"
      - "traefik.http.routers.api-insecure.entrypoints=web"
      - "traefik.http.routers.api-insecure.middlewares=api-redirect-https"
      
      # Service Definition
      - "traefik.http.services.api-service.loadbalancer.server.port=5000"
      
      # Middleware for HTTPS Redirect
      - "traefik.http.middlewares.api-redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.api-redirect-https.redirectscheme.permanent=true"

  db:
    image: postgres:17
    container_name: crowdqr-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - crowdqr-network
    labels:
      - "traefik.enable=false"

networks:
  crowdqr-network:
    driver: bridge

volumes:
  db_data: